Repository CA-G12/song-rating-app, pull requests merged in 2022-08, with the labels that each got.

#4 Create file structure
  .gitignore
  package-lock.json
  package.json
  public/404.html
  public/500.html
  public/index.html
  public/js/main.js
  src/app.js
  src/index.js
  src/routes.js
Labels: approved

#6 make main style for front-end side
  package-lock.json
  public/css/style.css
  public/index.html
  public/js/index.js
  public/js/main.js
Labels: awaiting review

#8 wrote the request to the api and handled the data in frontiend"
  package-lock.json
  package.json
  public/index.html
  public/js/index.js
  src/app.js
  src/index.js
Labels: approved

#10 make 404.html page , 500.html page and re-render-data in index js fr…
  public/404.html
  public/500.html
  public/css/error.css
  public/images/error.png
  public/js/index.js
  src/app.js
Labels: awaiting review

#11 Fixing heroku configurations
  package-lock.json
  package.json
  procfile
  src/app.js
  src/index.js
Labels: approved

#14 adding routers and separating calls into different files
  src/app.js
  src/controllers/404error.js
  src/controllers/500error.js
  src/controllers/index.js
  src/controllers/search-song.js
  src/routers/error.js
  src/routers/search.js
Labels: approved

#16 13 make dom front js
  package-lock.json
  public/js/index.js
Labels: awaiting review

#18 fixing modules errors
  src/app.js
  src/controllers/index.js
  src/routers/error.js
  src/routers/search.js
  src/routes.js
Labels: awaiting review

#20 wrote tests
  tests/test.js
Labels: approved

#21 19 make some static data
  public/css/style.css
  public/index.html
  public/js/index.js
  src/controllers/search-song.js
Labels: approved

#22 Writing readme
  README.md
  package.json
Labels: documentation, awaiting review
